# Site settings
title: Intent Docs
footerTitle: À propos
email: contact@intent-technologies.eu
phone: +33 9 72 30 91 51
description: > # this means to ignore newlines until "baseurl:"
  Intent Technologies opere le premier système d’exploitation du bâtiment connecté. Une plateforme unique et partagée entre tous les acteurs, services et équipements. Pour vous aider à maîtriser vos données et distribuer vos services à coûts maîtrisés.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://127.0.0.1:4000" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
